owner: alzee
repo: up

sites:
  - name: itove.com
    url: https://itove.com
  - name: img.itove.com
    url: https://img.itove.com
  - name: zhibao.itove.com
    url: https://zhibao.itove.com
  
status-website:
  name: Upptime
  cname: up.itove.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  user-agent: github-alzee-up
  theme: dark
